### ISSUE TITLE
Problem with the number of records in parent table, not having children

### ISSUE THREAD

**Issue by vitaliyb1** [mfragkoulis/PiCO_QL#27]
Dear Sir/Madam,

I'm trying PicoQL for use in telecommunications commercial software.
Legacy server is running with logs typically turned off, and PicoQL seems to present a viable approach to troubleshooting, not involving any logging/memory overhead.
Most simple queries work just fine, while lack of indexing on virtual tables make some more complex queries (e.g., those using group by) slow.

There are, however, some simple queries that do not work properly too.

I have the following PicoQL tables:

CREATE STRUCT VIEW Child
( 
      data TEXT FROM m_data
)$     

CREATE VIRTUAL TABLE child
USING STRUCT VIEW Child
WITH REGISTERED C TYPE std::list<Child*>$

CREATE STRUCT VIEW Parent
( 
   data TEXT FROM m_data,
   FOREIGN KEY( child_id) FROM m_children REFERENCES child
)$   

CREATE VIRTUAL TABLE parent
USING STRUCT VIEW Parent
WITH REGISTERED C NAME parent
WITH REGISTERED C TYPE std::vector<Parent*>$

///////////////////////////////////////////////////////////////////////////////////////

In C/C++ sources, I have:

struct Child
{
const char *m_data;
}.

struct Parent
{
const char _m_data;
std::list<Child_> m_children;
};.

///////////////////////////////////////////////////////////////////////////////////////

I would like to find number of parents that have some children, using the following query:

select count( distinct c1.rownum )
from parent c1, child c2
where 
c2.base=c1.child_id 

///////////////////////////////////////////////////////////////////////////////////////

However, this valid query does not work, it joins Parent to the Child with "(empty)" in all fields, if there are no children at all.

The hack that can be used is:

select count( \* ) from parent 
where exists( select \* from child c2 where c2.base=c1.child_id and c2.rownum <> "(empty)" ) 

//////////////////////////////////////////////////////////////////////////////////////////

Can this please be fixed? Please let me know if you need more info.

Thank you,
Vitaly Barinov

P.S. 
Also, I have some other notes/observations about PicoQL library. 
Please let me know if you are interested in me getting them submitted.

**Comment by mfragkoulis** [comment]
Dear Vitaly,

Nice to hear from you, that's a very interesting use case.
Let me see what I can do.
I'll get back to you soon.

Kind regards,
Marios

**Comment by vitaliyb1** [comment]
Hi Marios,

Thanks a lot for such a quick response.

Looks like the work-around I mentioned is also used in one of your examples:

% PiCO QL query

SELECT P.name, P.axisRotation, min(SP.axisRotation) 
FROM Planet AS P 
JOIN SatellitePlanet AS SP 
ON SP.base = P. satellites_id
WHERE P.onScreen
AND P.axisRotation > SP.axisRotation 
AND SP.base NOT LIKE '(empty)' 
GROUP BY P.name 
ORDER BY P.axisRotation DESC;

I mean "AND SP.base NOT LIKE '(empty)' ".

Here are some notes on my library use (unrelated to this particular problem):
1. I'm testing the library on Windows (single-threaded version). It ported pretty well (I did not port multi-threaded version, though. That would require using WinThreads instead of POSIX threads etc. but I only need single-threaded version).
2. I wish library had the way to supply SQLite3 pragmas (as kv-list?) through API call (I hacked register_table for the sake of the test).
3. I wish Swill were optional. We already have embedded Web-server, It looks like not a difficult task to get rid of Swill, however, it would be much easier if library allowed not to link with it (see API suggestions below).
4.  Some tables can be pretty large (hundreds of thousands or even millions of items). On those collections many queries take a lot of time, so there should be the way to interrupt the query (see API suggestion below).
5. SQLite3 allows user-defined functions. I wish they were allowed by PicoQL as well. If you expose DB handle, user can call sqlite3_create_function directly. That is not very elegant, though. Instead, you could introduce functions support directly in your DSL and hide SQLite3 details from user.

Here is the suggested new API (in addition to existing one):

pico_ql_init( db_pragmas )
pico_ql_exec_query( sql, callback ); // would call callback with sqlite3_stmt  to call sqlite3_step() on it.
pico_ql_register_progress_callback() // to report query progress; would call sqlite3_progress_handler(...)
pico_ql_interrupt() // would call sqlite3_interrupt(...) in another thread
pico_ql_shutdown()

I can implement this API itself but it would require me documenting every change (as Apache license requires), besides, it may be useful to other potential users.

pico_ql_serve() would never be called (and Swill would not be used). 
Instead, pico_ql_exec_query() would be used.

Cheers,
Vitaly

**Comment by mfragkoulis** [comment]
Hi Vitaly,

I have opened a new branch (issue27) and pushed a commit that hopefully deals with this issue. There is now an example (examples/Parentchild) that reflects your use case in order to help you test the new query behavior. Specifically, I tested the queries you specified (you can find them in ParentChild/pico_ql_test.c) and they seem to result in the desired outcome (see Parentchild/parentchild_test_success.txt). Please let me know whether this solution is satisfying in order to merge the branch.

Regarding the other issues/features you mention above, I find them valuable to have.
Would you like to open an issue for each one of them prioritised by importance for your case?
Please note that I will do my best to tackle them eagerly, but, as this effort comes in addition to my usual workload, unfortunately I can't commit to a milestone.

Cheers,
Marios

**Comment by vitaliyb1** [comment]
Thank you, Marios.

I will try your new code and let you know the results.

I have opened several new issues, as you advised.

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
The fix confirmed. I think, it is safe to merge the branch.

Thank you,
Vitaly

**Comment by mfragkoulis** [comment]
Branch merged. Closing this issue.
Thank you Vitaly for your help.
