### ISSUE TITLE
Swill-less configuration/API

### ISSUE THREAD

**Issue by vitaliyb1** [mfragkoulis/PiCO_QL#28]
Priority:High

Hi Marios,

This is the request to have the ability not to link with Swill.

The reasons for that are as follows:
1. Swill is under LGPL, that requires linking with it dynamically only. For me, this is huge drawback.
2. Swill has porting issues on Windows.
3. If app already has embedded WebServer, it is undesirable to have the second one.

Now pico_ql_serve() does not all the work.

I suggest the following new API to support Swill-less configuration

pico_ql_init( db_pragmas ) // open SQLite db here and keep the handle
pico_ql_exec_query( sql, callback ); // would call callback with sqlite3_stmt to call sqlite3_step() on it.
pico_ql_shutdown() // close SQLite db here

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
Hi Marios, 

I don't want to be bugging you but is there any progress?

Also, do you have any rough plans for other tickets as well?

I understand your business and that you cannot commit for a milestone but I need to know what to expect.

Say, if it is second half of 2017 I will probably try hacking the lib myself or even postpone this direction till better times.

Thank you much in advance,
Vitaly

**Comment by mfragkoulis** [comment]
Hi Vitaly,

I started working on the new API, but I had to put it on hold to sprint for another piece of work that is a priority this period.
I expect this line of work to end this week.
If there is a further delay I will let you know, but in any case I do not think it will take more than a couple of weeks.
Then I will be able to continue my work on the new API.

Kind regards,
Marios

**Comment by mfragkoulis** [comment]
Hi Vitaly,

Just a heads up that I am working on this as of today.

Cheers,
Marios

**Comment by mfragkoulis** [comment]
Hi Vitaly,

Just pushed a new branch (ng-api) where the API is updated in the lines of your proposal.
Please let me know how this looks.

Cheers,
Marios

**Comment by vitaliyb1** [comment]
Hi Marios,

I have checked the changed files.

The API changes roughly correspond to what I have requested.

However, I have the following quick notes/questions (some are unrelated to API):
1. Could you provide short (schematic) example how this new API will be used (call init, then reqister, then exec, then shutdown), with Swill and without?
2.  It is not clear how long-running query can be interrupted (issue #30). sqlite3 *db is not exposed anywhere, nor there is some other API routine to interrupt the query.
3. It is not clear how to report the progress of long-running query (issue #29).
4. Why do you need this FILE _f argument? Is it for diagnostics? If so, it is better to pass the printf-like callback, instead of FILE_, as diagnostics should be printed using existing application logging method.
5. Could you move all variable declarations in generated code to the beginning of the scope? Otherwise, the generated C-code does not compile on Windows.

Best regards,
Vitaly

**Comment by mfragkoulis** [comment]
Hi Vitaly,

Thank you for your comments.
1. You can check out [examples/Parentchild/main.cpp](https://github.com/mfragkoulis/PiCO_QL/blob/ng-api/examples/Parentchild/main.cpp).
   In brief:
   - pico_ql_register()
   - pico_ql_init()
   - pico_ql_exec()
   - pico_ql_shutdown()
2. The changes do not fix issue #29. I'll be glad to work on it as soon as we close this one.
3. Ditto.
4. No, it is for outputting the result set to the desired destination.
   This need emerged naturally from the different step functions (see [pico_ql_step.c](https://github.com/mfragkoulis/PiCO_QL/blob/ng-api/src/pico_ql_step.c)) that were already part of PiCO QL.
   There is a function for each different use case (html, json, text).
   I thought this is what you wanted unless the handling of the result set is not carried out by the callback passed to pico_ql_exec_query().
   Would you like to elaborate on the design that would work for you?
5. Sure. I'll let you know once I complete it.

Kind regards,
Marios

**Comment by vitaliyb1** [comment]
Hi Marios,
1. I have reviewed the examples. They are understandable.
2. OK to pospone issue #30 implementation till later.
3. OK to pospone issue #29 implementation till later.
4.  I don't particularly like this FILE approach for the following reasons:
    a) In general, it is not such a good idea to create temp file for each result-set. As those can be millions (including those made programmatically), it can overflow the /tmp partition (on Windows, using temp files may also come across the problems with permissions). 
    b) You basically use FILE in place of stream abstraction, which would be much more suitable. In C++, you could have used std::ostream (fstream, stringstream) etc. without changes in the API. How about creating C++ API with stream instead of FILE? That way would not have to add new API methods. If you want to stick with C then I need to get the direct access to the result-set (sqlite3_stmt), and I would use my own JSON generation routines to generate the response in memory (without any intermediate temporary files).
5. Thank you. As an alternative, you may think about generating C++ code. Just renaming files to .cpp would make compilation errors go away.

Best wishes,
Vitaly

**Comment by mfragkoulis** [comment]
Hi Vitaly,

I decided to diverge the development of the C++ version of PICO QL in order to be able to use modern C++ features.
Consequently:
- the query execution function now uses a string stream to carry the result set (answers comment 2  reported above) and
- the library's code is entirely C++ (answers comment 5 reported above).

I have pushed the new changes.
How does this look?

Kind regards,
Marios

**Comment by vitaliyb1** [comment]
Hi Marios,

I hope you have not used any modern C++ (11/14) features, have you? Some of my compilers will choke up on them, and there is no way for now to upgrade the compilers.

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
Hi Marios,

Some notes: 

1) Since you introduced picoQL namespace, you can drop pico_ql_ prefix in API functions names.
2) I already link with SQLite, and it would be nice if you put the content of  sqlite3.h/sqlite3.cpp under HAS_SQLITE ifndef.

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
Hi Marios,

I have briefly reviewed the changes in API and implementation (I did not compile new code, though).
They look good.

Best regards,
Vitaly

**Comment by dspinellis** [comment]
The `pico_ql_` should be retained for C bindings, no?  This could be done with a macro:
```
#ifdef __cplusplus
#define pico_ql_name(x) x
#else 
#define pico_ql_name(x) (pico_ql_ ## x)
#endif

int pico_ql_name(register_table)(int argc,...);
```

**Comment by dspinellis** [comment]
@vitaliyb1 Please also note that in https://github.com/dspinellis/swill I maintain a SWILL library that compiles under Windows.

**Comment by vitaliyb1** [comment]
I have the following reasons not to use Swill:

-- It is under LGPL, which forces me to link with it dynamically, which is not acceptable
-- I need to completely control the query format / result-set format, as it will be used by software, and not by the user in interactive mode (where Swill use is justified)

Also, Swill compiles on Windows no problem but I can only run the app as administrator, since such functions as tmpfile() require so on Windows.
