### ISSUE TITLE
Ability to interrupt the query

### ISSUE THREAD

**Issue by vitaliyb1** [mfragkoulis/PiCO_QL#30]
Priority:Medium

Hi Marios,

Is is of importance to have the ability to interrupt the query.

It can be implemented, e.g., as following API routine:

pico_ql_interrupt() // would call sqlite3_interrupt(...) in another thread

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
Hi Marios, 

Any plans on implementing this?

I need at least  #28, windows port and this one to start using the library.

Best regards,
Vitaly

**Comment by mfragkoulis** [comment]
Hi Vitaly,

Yes, during the Christmas holidays.

Kind regards,
Marios

**Comment by mfragkoulis** [comment]
Hi Vitaly,

Just a heads up that I'm working on this.

Kind regards,
Marios

**Comment by mfragkoulis** [comment]
Hi Vitaly,

I have completed working on the set of issues you opened.
Each is addressed by a commit.
Therefore, I close the issues.
Feel free to comment if anything does not fall into place.

Kind regards,
Marios

**Comment by vitaliyb1** [comment]
Thank you much, Marios.
I will try to check them all out in the upcoming couple of weeks and will let you know about the results.

Cheers,
Vitaly
