### ISSUE TITLE
Library port to Windows

### ISSUE THREAD

**Issue by vitaliyb1** [mfragkoulis/PiCO_QL#34]
Priority:Low

Hi Marios,

Library is easily portable to Windows.

It would be great if MSVS 2010 project file (or just makefile) was supplied to build the library on Windows.

Best regards,
Vitaly

**Comment by vitaliyb1** [comment]
Variable declarations in generated code should be moved to the scope beginning to get it compiled as C source with MSVS 2010.
Posix declarations on Windows should be replaced with WinThreads, so, ideally, there should be very thin/compact threads abstraction layer implemented in the library.

**Comment by mfragkoulis** [comment]
Variable declarations have been fixed.
The code compiles under Windows 10  on Cygwin's environment.
Unfortunately I don't have easy access to MSVS.
